# .github/workflows/backend-cicd.yaml

name: Run CICD on backend
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Pull repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: Prepare env file
      run: |
        touch backend/.env
        echo ${{ secrets.mongodb_path }} > backend/.env
        cat backend/.env

    - name: Run backend tests
      run: |
        cd backend
        npm ci
        npm test

  deploy-gae:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Pull repository
      uses: actions/checkout@v3

    - name: Authenticate with google app engine
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.gcp_credentials }}

    - name: Prepare env file
      run: |
        touch backend/.env
        echo ${{ secrets.mongodb_path }} > backend/.env
        
    - name: Deploy backend to google app engine
      uses: google-github-actions/deploy-appengine@v0
      with:
        working_directory: backend
        deliverables: app.yaml
        promote: false
