name: Run CI tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Use MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'
          mongodb-replica-set: simplenoteapp
          mongodb-port: 27017

      - run: |
          cd backend
          npm ci
          npm run build --if-present
          npm test
          cd ..

      - run: |
          cd frontend
          npm i --save node-pre-gyp
          npm ci
          npm run build --if-present
          npm test
          cd ..
